[[redirects]]
from = "/scan/192.168.88.1"
to = "http://192.168.88.1/rpc/Shelly.GetInfo"
status = 200
force = false

[[redirects]]
from = "/scan/192.168.88.2"
to = "http://192.168.88.2/rpc/Shelly.GetInfo"
status = 200
force = false

[[redirects]]
from = "/scan/192.168.88.3"
to = "http://192.168.88.3/rpc/Shelly.GetInfo"
status = 200
force = false

[[redirects]]
from = "/scan/192.168.88.4"
to = "http://192.168.88.4/rpc/Shelly.GetInfo"
status = 200
force = false

[[redirects]]
from = "/scan/192.168.88.5"
to = "http://192.168.88.5/rpc/Shelly.GetInfo"
status = 200
force = false

[[redirects]]
from = "/scan/192.168.88.6"
to = "http://192.168.88.6/rpc/Shelly.GetInfo"
status = 200
force = false

[[redirects]]
from = "/scan/192.168.88.7"
to = "http://192.168.88.7/rpc/Shelly.GetInfo"
status = 200
force = false

[[redirects]]
from = "/scan/192.168.88.8"
to = "http://192.168.88.8/rpc/Shelly.GetInfo"
status = 200
force = false

[[redirects]]
from = "/scan/192.168.88.9"
to = "http://192.168.88.9/rpc/Shelly.GetInfo"
status = 200
force = false

[[redirects]]
from = "/scan/192.168.88.10"
to = "http://192.168.88.10/rpc/Shelly.GetInfo"
status = 200
force = false
